#include<iostream.h>
#include<conio.h>

class KBC
{
	public:
		char ch;

	public:

	void in()
	{
		cout<<endl<<"\t\t\t     KON BANEGA CROREPATI"<<endl;

		cout<<endl<<"________________________________________________________________________________";


		cout<<endl<<"Rules of Game :-"<<endl<<endl;

		cout<<endl<<"After Answering 10 Questions,"<<endl<<"Jackpot Que of Rs 7 CRORE Unlock's."<<endl;
		cout<<endl<<"Either if you answered the any Question wrong after won rs 10,000 or 3,60,000"<<endl<<"You were suppose to win only 10,000 or 3,60,000 depends on condition,"<<endl;
		cout<<endl<<"Or if you Quit You Won The Same Amount."<<endl;

		cout<<endl<<"________________________________________________________________________________";

	}

	void out()
	{
	     cout<<endl<<"Q1 for 2,000 Rs"<<endl;
	     cout<<endl<<"________________________________________________________________________________";
	     cout<<endl<<"Who is the first Prime Minister ofINDIA?"<<endl;

	     cout<<endl<<"(A) Jawaharlal Nehru   \t\t    (B) Narendra Modi";
	     cout<<endl<<"(C) Indra Gandhi       \t\t    (D) Mahatma Gandhi";

	     cout<<endl<<endl<<"Enter your Choice = ";
	     cin>>ch;
	     cout<<endl<<"________________________________________________________________________________";

	     if(ch=='a' || ch=='A')
	     {
		 cout<<endl<<endl<<"Congratulations you have won 2,000 Rs";

		 getch();
		 clrscr();

		 cout<<endl<<"Q2 for 4,000 Rs"<<endl;
		 cout<<endl<<"________________________________________________________________________________";
		 cout<<endl<<"Which team had won the first ever ODI(One Day International) World Cup?"<<endl;

		     cout<<endl<<"(A) India              \t\t    (B) Zimbabwe";
		     cout<<endl<<"(C) West Indies        \t\t    (D) England";

		     cout<<endl<<endl<<"Enter your Choice = ";
		     cin>>ch;
		     cout<<endl<<"________________________________________________________________________________";

		     if(ch=='c' || ch=='C')
		     {

				cout<<endl<<endl<<"Congratulations you have won 4,000 Rs";

				getch();
				clrscr();

				cout<<endl<<"Q3 for 6,000 Rs"<<endl;
				cout<<endl<<"________________________________________________________________________________";
				cout<<endl<<"Who is the Cheif Minister Of Rajasthan?"<<endl;

				cout<<endl<<"(A) Vasundhra Raje     \t\t    (B) Ashok Geloth";
				cout<<endl<<"(C) Sachin Pilot       \t\t    (D) Rahul Gandhi";

				cout<<endl<<endl<<"Enter your Choice = ";
				cin>>ch;

				cout<<endl<<"________________________________________________________________________________";

				if(ch=='b' || ch=='B')
				{

					cout<<endl<<endl<<"Congratulations you have won 6,000 Rs";

					getch();
					clrscr();

					cout<<endl<<"Q4 for 8,000 Rs"<<endl;
					cout<<endl<<"________________________________________________________________________________";
					cout<<endl<<"Which one of among them is the smallest city in the World?"<<endl;

					cout<<endl<<"(A) Greenwood City     \t\t    (B) Vatican City";
					cout<<endl<<"(C) San Marino City    \t\t    (D) Jerico City";

					cout<<endl<<endl<<"Enter your Choice = ";
					cin>>ch;

					cout<<endl<<"________________________________________________________________________________";
					if(ch=='b' || ch=='B')
					{
					      cout<<endl<<endl<<"Congratulations you have won 8,000 Rs";

						getch();
						clrscr();

						cout<<endl<<"Q5 for 10,000 Rs"<<endl;
						cout<<endl<<"________________________________________________________________________________";
						cout<<endl<<"Which team has won the most no. of IPL trophies?"<<endl;

						cout<<endl<<"(A) Chennai Super Kings\t\t    (B) Royal Challengers Banglore";
						cout<<endl<<"(C) Sunrises Hyderabad \t\t    (D) Mumbai Indians";

						cout<<endl<<endl<<"Enter your Choice = ";
						cin>>ch;
						cout<<endl<<"________________________________________________________________________________";
						if(ch=='D' || ch=='d')
						{


							cout<<endl<<endl<<"Congratulations you have won 10,000 Rs";

							getch();
							clrscr();

							cout<<endl<<"Q6 for 20,000 Rs"<<endl;
							cout<<endl<<"________________________________________________________________________________";
							cout<<endl<<"Real Name of TMKOC character Jethalal Gada?"<<endl;

							cout<<endl<<"(A) Dilip Joshi        \t\t    (B) Shalesh Lodha";
							cout<<endl<<"(C) Amit Dhutt         \t\t    (D) Gulab Kumar";

							cout<<endl<<endl<<"Enter your Choice = ";
							cin>>ch;

							cout<<endl<<"________________________________________________________________________________";
							if(ch=='A' || ch=='a')
							{
								cout<<endl<<endl<<"Congratulations you have won 20,000 Rs";

								getch();
								clrscr();

								cout<<endl<<"Q7 for 40,000 Rs"<<endl;
								cout<<endl<<"________________________________________________________________________________";
								cout<<endl<<"Which Player Has took the Most Wickets in Test Cricket?"<<endl;

								cout<<endl<<"(A) Shane Warne        \t\t        (B) Anil Kumble";
								cout<<endl<<"(C) Muttiah Muralitharan\t\t(D) James Anderson";

								cout<<endl<<endl<<"Enter your Choice = ";
								cin>>ch;

								cout<<endl<<"________________________________________________________________________________";
								if(ch=='C' || ch=='c')
								{

									cout<<endl<<endl<<"Congratulations you have won 40,000 Rs";

									getch();
									clrscr();

									cout<<endl<<"Q8 for 80,000 Rs"<<endl;
									cout<<endl<<"________________________________________________________________________________";
									cout<<endl<<"Full name of Bhagat Singh?"<<endl;

									cout<<endl<<"(A) Bhagat Singh       \t\t        (B) Bhagat Singh Bhago Wale";
									cout<<endl<<"(C) Bhagat Gurumukh Singh\t\t(D) Bhagat Singh Sandhu";

									cout<<endl<<endl<<"Enter your Choice = ";
									cin>>ch;
									cout<<endl<<"________________________________________________________________________________";
									if(ch=='D' || ch=='d')
									{


										cout<<endl<<endl<<"Congratulations you have won 80,000 Rs";

										getch();
										clrscr();

										cout<<endl<<"Q9 for 160,000 Rs"<<endl;
										cout<<endl<<"________________________________________________________________________________";
										cout<<endl<<"Most sensetive organ in Human Body?"<<endl;

										cout<<endl<<"(A) Heart              \t\t    (B) Brain";
										cout<<endl<<"(C) Tongue             \t\t    (D) Skin";

										cout<<endl<<endl<<"Enter your Choice = ";
										cin>>ch;

										cout<<endl<<"________________________________________________________________________________";
										if(ch=='D' || ch=='d')
										{


											cout<<endl<<endl<<"Congratulations you have won 160,000 Rs";


											getch();
											clrscr();

											cout<<endl<<"Q10 for 320,000 Rs"<<endl;
											cout<<endl<<"________________________________________________________________________________";
											cout<<endl<<"Highest Individual Score by an Player in ODI's?"<<endl;

											cout<<endl<<"(A) 219                \t\t    (B) 264";
											cout<<endl<<"(C) 237                \t\t    (D) 270";

											cout<<endl<<endl<<"Enter your Choice = ";
											cin>>ch;

											cout<<endl<<"________________________________________________________________________________";
											if(ch=='B' || ch=='b')
											{


											cout<<endl<<endl<<"Congratulations you have won 320,000 Rs";


											getch();
											clrscr();

											cout<<endl<<"Q11 for 640,000 Rs"<<endl;
											cout<<endl<<"________________________________________________________________________________";
											cout<<endl<<"Highest Individual Score by an Player in T20I's?"<<endl;

											cout<<endl<<"(A) 175                \t\t    (B) 172";
											cout<<endl<<"(C) 162                \t\t    (D) 199";

											cout<<endl<<endl<<"Enter your Choice = ";
											cin>>ch;
											cout<<endl<<"________________________________________________________________________________";
											if(ch=='B' || ch=='b')
											{

											cout<<endl<<endl<<"Congratulations you have won 640,000 Rs";

											getch();
											clrscr();

											cout<<endl<<"Q12 for 12,80,000 Rs"<<endl;
											cout<<endl<<"________________________________________________________________________________";
											cout<<endl<<"Which team won the first ever World Test Championship?"<<endl;

											cout<<endl<<"(A) England            \t\t    (B) New Zealand";
											cout<<endl<<"(C) Australia          \t\t    (D) India";

											cout<<endl<<endl<<"Enter your Choice = ";
											cin>>ch;

											cout<<endl<<"________________________________________________________________________________";
												if(ch=='b' || ch=='B')
												{

													cout<<endl<<endl<<"Congratulations you have won 12,80,000 Rs";


													getch();
													clrscr();
													cout<<endl<<"Q13 for 25,60,000 Rs"<<endl;
													cout<<endl<<"________________________________________________________________________________";
													cout<<endl<<"Which team won the first ever World Test Championship?"<<endl;

													cout<<endl<<"(A) Atal Bihari Vajpayee\t\t        (B) Dr. B.R.Ambedkar";
													cout<<endl<<"(C) A.P.J Abdul Kalam      \t\t        (D) Mahatma Gandhi";

													cout<<endl<<endl<<"Enter your Choice = ";
													cin>>ch;

													cout<<endl<<"________________________________________________________________________________";
														if(ch=='b' || ch=='B')
														{

															cout<<endl<<endl<<"Congratulations you have won 25,60,000 Rs";


															getch();
															clrscr();
															cout<<endl<<"Q14 for 51,20,000 Rs"<<endl;
															cout<<endl<<"________________________________________________________________________________";
															cout<<endl<<"Jallianwala Bagh Massacre held on ehich date?"<<endl;

															cout<<endl<<"(A) 13 April 1919      \t\t    (B) 14 Feb 1919";
															cout<<endl<<"(C) 30 May 1906        \t\t    (D) 6 March 1906";

															cout<<endl<<endl<<"Enter your Choice = ";
															cin>>ch;

															cout<<endl<<"________________________________________________________________________________";

																if(ch=='a' || ch=='A')
																{

																	cout<<endl<<endl<<"Congratulations you have won 51,20,000 Rs";


																	getch();
																	clrscr();
																	cout<<endl<<"Q15 for 1,00,00,000 Rs"<<endl;
																	cout<<endl<<"________________________________________________________________________________";
																	cout<<endl<<"On Which Date INDIAN Team Played Their 1st Test Match?"<<endl;

																	cout<<endl<<"(A) 15 Aug. 1947       \t\t    (B) 14 Feb 1934";
																	cout<<endl<<"(C) 25 June 1932       \t\t    (D) 6 March 1951";

																	cout<<endl<<endl<<"Enter your Choice = ";
																	cin>>ch;

																	cout<<endl<<"________________________________________________________________________________";

																		if(ch=='c' || ch=='C')
																		{

																			cout<<endl<<endl<<"Congratulations you have won 1 Crore Rs";

																			getch();
																			clrscr();
																			cout<<endl<<"Jackpot Q for 7,00,00,000 Rs"<<endl;
																			cout<<endl<<"________________________________________________________________________________";
																			cout<<endl<<"What was the Famous Slogan of Bhagat Singh?"<<endl;

																			cout<<endl<<"(A) Go Back Simmon Go Back\t\t (B) Angrezo Bharat Chhodo";
																			cout<<endl<<"(C) Karo ya Maro       \t\t         (D) Inquilab Zindabadh";

																			cout<<endl<<endl<<"Enter your Choice = ";
																			cin>>ch;

																			cout<<endl<<"________________________________________________________________________________"<<endl;

																				if(ch=='d' || ch=='D')
																				{
																					cout<<"\t\t    Congratulation you have Won 7 CRORE Rs"<<endl;

																					cout<<endl<<"________________________________________________________________________________";
																				}
																				else
																				{
																				cout<<endl<<"Incorrect Choice"<<endl;
																				cout<<"Correct answer is Option (C)"<<endl;
																				cout<<endl<<"Congrats you have won 320,000 Rs";
																				cout<<endl<<"Better Luck Next Time";
																				}

																		}
																		else
																		{
																			cout<<endl<<"Incorrect Choice"<<endl;
																			cout<<"Correct answer is Option (C)"<<endl;
																			cout<<endl<<"Congrats you have won 320,000 Rs";
																		}

																}
																else
																{
																	cout<<endl<<"Incorrect Choice"<<endl;
																	cout<<"Correct answer is Option (A)"<<endl;
																	cout<<endl<<"Congrats you have won 320,000 Rs";
																}

														}
														else
														{
															cout<<endl<<"Incorrect Choice"<<endl;
															cout<<"Correct answer is Option (B)"<<endl;
															cout<<endl<<"Congrats you have won 320,000 Rs";
														}

												}
												else
												{
												cout<<endl<<"Incorrect Choice"<<endl;
												cout<<"Correct answer is Option (B)"<<endl;
												cout<<endl<<"Congrats you have won 320,000 Rs";
												}

											}
											else
											{
											cout<<endl<<"Incorrect Choice"<<endl;
											cout<<"Correct answer is Option (b)"<<endl;
											cout<<endl<<"Congrats you have won 320,000 Rs";
											}


											}
											else
											{
											cout<<endl<<"Incorrect Choice"<<endl;
											cout<<"Correct answer is Option (b)"<<endl;
											cout<<endl<<"Congrats you have won 10,000 Rs";
											}


										}
										else
										{
										cout<<endl<<"Incorrect Choice"<<endl;
										cout<<"Correct answer is Option (D)"<<endl;
										cout<<endl<<"Congrats you have won 10,000 Rs";
										}


									}
									else
									{
										cout<<endl<<"Incorrect Choice"<<endl;
										cout<<"Correct answer is Option (D)"<<endl;
										cout<<endl<<"Congrats you have won 10,000 Rs";
									}


								}
								else
								{
									cout<<endl<<"Incorrect Choice"<<endl;
									cout<<"Correct answer is Option (C)"<<endl;
									cout<<endl<<"Congrats you have won 10,000 Rs";
								}

							}
		else
		{
			cout<<endl<<"Incorrect Choice"<<endl;
			cout<<"Correct answer is Option (A)"<<endl;
			cout<<endl<<"Congrats you have won 10,000 Rs";
		}




						}
						else
						{
						cout<<endl<<"Incorrect Choice"<<endl;
						cout<<"Correct answer is Option (D)"<<endl;
						cout<<endl<<"Congrats you have won 8,000 Rs";
						}

					}
					else
					{
					cout<<endl<<"Incorrect Choice"<<endl;
					cout<<"Correct answer is Option (B)"<<endl;
					cout<<endl<<"Congrats you have won 6,000 Rs";
					}


				}
				else
				{
				cout<<endl<<"Incorrect Choice"<<endl;
				cout<<"Correct answer is Option (B)"<<endl;
				cout<<endl<<"Congrats you have won 4,000 Rs";
				}
		     }
		     else
		     {
			cout<<endl<<"Incorrect Choice"<<endl;
			cout<<"Correct answer is Option (C)"<<endl;
			cout<<endl<<"Congrats you have won 2,000 Rs";
		     }
	     }
	     else
	     {
		cout<<endl<<"Incorrect Choice"<<endl;
		cout<<"Correct answer is Option (A)"<<endl;
		cout<<endl<<"You Won Nothing";
	     }
	}


};

void main()
{
clrscr();
		KBC obj1;
		obj1.in();

		getch();
		clrscr();

		obj1.out();
getch();
}